### ISSUE TITLE
Ability to save streams I've added

### ISSUE THREAD

**Issue by cmicek1** [PhysioLabXR/PhysioLabXR-Community#135]
I'm exploring using PhysioLabXR as a replacement for LabRecorder because we've run into some issues saving our data (turns out a remote collaboration across continents is challenging). Immediate pain point I'm noticing is there doesn't seem to be an easy way to save streams once I add them, so that I can close the program and reopen it and just have them there in the Stream tab, or have them easy to load. Having to add each stream by name and update channel names manually is kind of cumbersome, and I'd like to not need to do that every time I begin a recording session. In LabRecorder, all published streams are discovered automatically; this would be useful functionality to include in the future.

**Comment by HaowenWeiJohn** [comment]
Hi Christopher,

Thank you for contacting us. All the features you mentioned have been developed but are not explicitly exposed to the user at this moment. Currently, any modifications you make to each stream, such as channel names and group names, are saved when you close the program normally (as long as you do not kill the program).

Additionally, there is a method to create an "experiment preset" that allows you to save a group of streams that you want to add. However, this function is not explicitly exposed to the user at this point.

We could schedule a meeting at your convenience this week if you need further assistance.

Best regards,
Haowen 'John' Wei & Ziheng 'Leo' Li
hw2892@columbia.edu
